# Generated by Django 5.1 on 2024-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='default', max_length=400),
            preserve_default=False,
        ),
    ]
